# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSbt():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sbt(self):
    self.driver.get("https://www.sbtjapan.com/")
    self.driver.set_window_size(2576, 1426)
    self.driver.find_element(By.CSS_SELECTOR, "#sidebar_maker_toyota > .modelname_stocknum").click()
    self.vars["stockID3"] = self.driver.find_element(By.LINK_TEXT, "2016/1 TOYOTA VITZ F").text
    self.driver.find_element(By.ID, "container").click()
    self.driver.find_element(By.ID, "container").click()
    self.driver.find_element(By.ID, "container").click()
    self.vars["stockid1"] = self.driver.title
    self.vars["storeid2"] = self.driver.title
    self.vars["stockID2"] = self.driver.find_element(By.LINK_TEXT, "2019/5 TOYOTA VITZ F SAFETY EDITION III").text
    self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(5) > .grid-item:nth-child(1) .grid-hdg").click()
    self.driver.find_element(By.ID, "year_f").click()
    dropdown = self.driver.find_element(By.ID, "year_f")
    dropdown.find_element(By.XPATH, "//option[. = '2016']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".searchButton").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".searchButton")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.execute_script("window.scrollTo(0,673)")
    element = self.driver.find_element(By.LINK_TEXT, "2019/1 TOYOTA VITZ F SAFETY EDITION II")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.vars["stockID1"] = self.driver.find_element(By.LINK_TEXT, "2019/1 TOYOTA VITZ F SAFETY EDITION II").text
  
